### ISSUE TITLE
Prod build routes not working

### ISSUE THREAD

**Issue by msimonc** [JaimeStill/react-loadable-demo#1]
Thanks for this,

When I added a route it worked in Dev but not in Prod,

**Comment by JaimeStill** [comment]
@msimonc, I would need more detail than that to help you troubleshoot. Did the default route work in production?

**Comment by msimonc** [comment]
Getting there... if I `yarn build` then `http-server build/` it doesn't work until I
move all the build/* files except index.html into a folder named build/react-loadable-demo

Then it works, including the chunking :)

**Comment by JaimeStill** [comment]
As this is not an issue related to this repo (this is merely a personal repo intended for me to remember how to do routing with `react-loadable`), I'm going to go ahead and close this. I would suggest reviewing `react-router` and `react-loadable` to get a better understanding of how to use them for your needs.
